### PR TITLE
Add compiler/jq.vim

### LINKED ISSUE #12: [feature] Add compiler/jq.vim
Parse

```
❯ jq -r '{' /dev/null
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
{
jq: 1 compile error
```

to

```
:make
top-level|1|unexpected $end (Unix shell quoting issues?)
```

`ftplugin/jq.vim` contains `compiler jq`

Screenshot_20221028_174237

### PR DESCRIPTION
**Pull request by Freed-Wu**
Fix #12

### CODE REVIEW

**Comment by Freed-Wu** [comment]
@vito-c

**Comment by vito-c** [comment]
Hi let me take a look tonight sorry I missed this

**Comment by Freed-Wu** [comment]
Hey, have you taken a look? @vito-c

**Comment by vito-c** [comment]
on it now sorry for the delay

**Pull request merged**
